Registration endpoint
mrPTqp/realworld-impl pull request #1
Opened 2020-05-22 09:00 UTC by mrPTqp

2020-05-22 09:58 UTC, daddyingrave requested changes

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/_exceptions/AppExceptionHandler.java
> +
Здесь и ниже, зачем тут пустая строка?

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/_security/MyUserDetails.java
> +public class MyUserDetails implements UserDetails {
`MyUserDetails` звучит как то хелловорлдно :)
Варианты: `UserDetailsImpl`, `ConduitUserDetails`

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/_security/MyUserDetailsService.java
> +                .flatMap(customerRepository::findByEmail)
Метод называется `loadUserByUsername` но здесь ты ищешь `customer` с помощью `findByEmail`.
Звучит это все не очень консистентно.

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/_security/MyUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("Cannot find user with email=" + username));
`"Cannot find user with email=" + username`
а?

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/_security/SecurityConfiguration.java
> +        configuration.setAllowedMethods(asList("HEAD",
мне не нравится такое форматирование. вот варианты:
```java
configuration.setAllowedMethods(
    asList("HEAD", "GET", "POST", "PUT", "DELETE", "PATCH")
);

configuration.setAllowedMethods(
    asList(
        "HEAD", 
        "GET", 
        "POST", 
        "PUT", 
        "DELETE", 
        "PATCH"
    )
);
```
Второй вариант больше скале подходит, но в данной ситуации мне кажется первый вполне ок

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/comments/controllers/AddCommentController.java
> +            @PathVariable("slug") String slug,
Форматируй консистентно.

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/comments/controllers/AddCommentController.java
> +            @PathVariable("slug") String slug,
Если делаешь так https://github.com/mrPTqp/realworld-impl/pull/1/files#diff-2b126e75da2a357a91ea287b13231a08R13 до делай так везде

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/comments/entities/Comment.java
> +    @ManyToOne(fetch = FetchType.EAGER, cascade = {CascadeType.MERGE, CascadeType.PERSIST})
Почему `EAGER`?

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/profiles/controllers/FollowUserController.java
> +public class FollowUserController {
Выглядит так что этот контроллер и `GetProfileController`
Ну тоесть все методы что оперируют одной сущностью, в общем случае должны быть в одном контроллере

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/tags/controllers/GetTagsController.java
> +public class GetTagsController {
`TagsController`

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/profiles/controllers/FollowUserController.java
> +public class FollowUserController {
После мержа это наверное должен быть либо `ProfileController` либо `UserController`

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/controllers/GetCurrentUserController.java
> +public class GetCurrentUserController {
Это не должен быть отдельный контроллер

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/controllers/RegistrationController.java
> +public class RegistrationController {
Это скорее всего, не должен быть отдельный контроллер

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/controllers/UpdateUserController.java
> +public class UpdateUserController {
Это скорее всего, не должен быть отдельный контроллер

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        customerRepository.findByEmail(registerCredentials.getEmail())
А вот так влезает по длине?
```java
customerRepository
    .findByEmail(registerCredentials.getEmail())
    .ifPresent(u -> throw new UserAlreadyExistException("User already exists! Choose a different name."));
```
если нет то можно на следующую строчку наврено месадж перенести

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        customerRepository.findByEmail(registerCredentials.getEmail())
ниже аналогично

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        User user = customerRepository.findById(id)
```java
customerRepository
    .findById(id)
    .orElseThrow(() -> new UserNotFoundException("User not found. Please check your id"));
```

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        User user = customerRepository.findById(id)
ну и ниже так же

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
давай вместо `properties` формата использовать `.yaml`

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        return new UserDto(
а нам точно на этом уровне нужно использовать Dto?

2020-05-22 09:58 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +            throw new RuntimeException("Wrong password, please try again");
А чо здесь не кастомный эксепшн?

2020-05-23 10:32 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/_exceptions/AppExceptionHandler.java
> +
хз, так красивее) удалил.

2020-05-23 10:33 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/_security/MyUserDetails.java
> +public class MyUserDetails implements UserDetails {
исправил

2020-05-23 10:44 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/_security/MyUserDetailsService.java
> +                .flatMap(customerRepository::findByEmail)
А вот я хз, как это исправить. Типа у интерфейса UserDetailsService только один метод loadUserByUsername, но моя цель - логиниться по email, и поэтому получается такой кавардак... Если знаешь как это обойти - подскажи плз

2020-05-23 10:45 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/_security/MyUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("Cannot find user with email=" + username));
Ну могу ввести дополнительную переменную
```private String email = username```
и дальше использовать ее.
Пойдет?

2020-05-23 10:51 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/_security/SecurityConfiguration.java
> +        configuration.setAllowedMethods(asList("HEAD",
Слушай, я эту херню скопипастил и не обратил внимание. Сейчас вообще осознал, что это всё прекрасно влезет в одну строку. Но твою мысль понял. Исправлено.
db5e7cca6767d85b12b9b7affbbc97f9aefde604

2020-05-23 10:55 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/comments/controllers/AddCommentController.java
> +            @PathVariable("slug") String slug,
Блин, чот не пойму чо ты имел ввиду. Ссылка ведет на коммит в целом, а не на какое-то конкретное место в нем

2020-05-23 11:23 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/_security/MyUserDetailsService.java
> +                .flatMap(customerRepository::findByEmail)
а ну да похуй )

2020-05-23 11:23 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/_security/MyUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("Cannot find user with email=" + username));
Всвязи с вышесказанным, пох )

2020-05-23 11:25 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/comments/controllers/AddCommentController.java
> +            @PathVariable("slug") String slug,
Хм, у меня ссылка нормально резолвится в и ведет в конкретную строку
![image](https://user-images.githubusercontent.com/12502267/82729555-305ab300-9d01-11ea-9775-462822ed707e.png)

2020-05-23 11:43 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/comments/controllers/AddCommentController.java
> +            @PathVariable("slug") String slug,
откорректировал форматирование принимаемых параметров в контроллере
63fc8f0564b0e9897580877216f515060e7b3c76

2020-05-23 11:50 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/comments/entities/Comment.java
> +    @ManyToOne(fetch = FetchType.EAGER, cascade = {CascadeType.MERGE, CascadeType.PERSIST})
потому что когда заходишь в статью, то хочешь видеть все комменты сразу. это было бы иначе, если бы в conduit была пагинация комментов, но там такого нет, как я понял (я добавил здесь более 20 комментариев, и пагинации не появилось https://demo.realworld.io/#/article/hola-peru-xslndj)

2020-05-23 12:45 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/profiles/controllers/FollowUserController.java
> +public class FollowUserController {
Исправлено 
fe9f395fd0c7d2719d7571f9c19f647136891da7

2020-05-23 12:45 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/tags/controllers/GetTagsController.java
> +public class GetTagsController {
Исправлено 
fe9f395fd0c7d2719d7571f9c19f647136891da7

2020-05-23 12:45 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/users/controllers/GetCurrentUserController.java
> +public class GetCurrentUserController {
Исправлено 
fe9f395fd0c7d2719d7571f9c19f647136891da7

2020-05-23 12:45 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/users/controllers/RegistrationController.java
> +public class RegistrationController {
Исправлено 
fe9f395fd0c7d2719d7571f9c19f647136891da7

2020-05-23 12:46 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/users/controllers/UpdateUserController.java
> +public class UpdateUserController {
Исправлено 
fe9f395fd0c7d2719d7571f9c19f647136891da7

2020-05-23 12:57 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        customerRepository.findByEmail(registerCredentials.getEmail())
Идеа не дает сделать так, как ты говоришь :( Она блок кода в лямбде форматирует на 3 разных строки 
```  customerRepository.findByEmail(registerCredentials.getEmail())
                .ifPresent(u -> **{
                    throw new UserAlreadyExistException("User already exists! Choose a different name.");
                }**);```

2020-05-23 12:59 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        customerRepository.findByEmail(registerCredentials.getEmail())
Менять правила идеи?

2020-05-23 13:02 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        customerRepository.findByEmail(registerCredentials.getEmail())
Посмотри, так пойдет?
7f94ba77d14af3ff24272f248a362131ce35d6fa

2020-05-23 13:02 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        User user = customerRepository.findById(id)
Исправлено 
7f94ba77d14af3ff24272f248a362131ce35d6fa

2020-05-23 14:12 UTC, mrPTqp commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
исправлено 
6e5649222183072511ed47e7a9d1c6f85d1024ca

2020-05-23 14:14 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        return new UserDto(
а что нужно использовать? Etity? Или вопрос устарел после нашего вчерашнего разговора в зуме?

2020-05-23 14:21 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +            throw new RuntimeException("Wrong password, please try again");
Теперь кастомный, ответ 403 Forbidden 
98f97844a079e5ad14c57c885cd7136bfbdf60c7

2020-05-23 14:54 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +            throw new RuntimeException("Wrong password, please try again");
Начал добавлять шифровщик паролей, и понял, что 403 здесь ни к чему. Теперь 401 UNAUTHORIZED.
1df230049c0cc47999c836f3a725c418ef8d3712

2020-05-23 17:13 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        customerRepository.findByEmail(registerCredentials.getEmail())
да отлично

2020-05-23 17:15 UTC, AndreyElagin commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
несмотря на то что у тебя полностью валидный yml получился, но стоит сделать немного по другому. вот здесь пример https://www.baeldung.com/spring-yaml

2020-05-23 17:15 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/users/service/CustomerServiceImpl.java
> +        return new UserDto(
да устарел

2020-05-23 17:24 UTC, daddyingrave requested changes

2020-05-23 17:24 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/articles/controllers/ArticleController.java
> +    public String favoriteArticle(@PathVariable("slug") String slug) {
Кажется, что семантически это что то типа addToFavorite

2020-05-23 17:24 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/articles/controllers/ArticleController.java
> +    public String unFavoriteArticle(@PathVariable("slug") String slug) {
А это removeFromFavorite

2020-05-23 17:34 UTC, mrPTqp commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
Исправлено
8bd0557fa921ce356e0c3c3996ebfde4bda4f1b3

2020-05-23 17:38 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/articles/controllers/ArticleController.java
> +    public String favoriteArticle(@PathVariable("slug") String slug) {
Исправлено
e2f25934c9e88771da8e631af5cb52cfa93a2985

2020-05-23 17:38 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/articles/controllers/ArticleController.java
> +    public String unFavoriteArticle(@PathVariable("slug") String slug) {
Исправлено
e2f25934c9e88771da8e631af5cb52cfa93a2985

2020-05-23 17:40 UTC, daddyingrave approved these changes

2020-05-23 18:22 UTC, merged