Add JWT auth. Add "/user" endpoint implementation (get current user)
mrPTqp/realworld-impl pull request #2
Opened 2020-05-25 20:21 UTC by mrPTqp

2020-05-27 15:43 UTC, daddyingrave requested changes
В целом все вроде ок, поправь секретный ключ только

2020-05-27 15:43 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/_security/JwtUtil.java
> +    private final String SECRET_KEY = "mrptqp";
Обяви этот ключ в application.yaml, тем самым ты его сможешь туда динамически подкидывать

2020-05-29 11:38 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/_security/JwtUtil.java
> +    private final String SECRET_KEY = "mrptqp";
Исправлено 4f6d39e635cd5f2e559f8115de226a1515df4346

2020-05-29 12:48 UTC, daddyingrave approved these changes

2020-05-29 13:14 UTC, merged