90 profile
mrPTqp/realworld-impl pull request #4
Opened 2020-06-01 21:04 UTC by mrPTqp

2020-06-02 12:35 UTC, daddyingrave requested changes

2020-06-02 12:35 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/profiles/service/ProfileServiceImpl.java
> +                ));
у тебя этот код повторяется несколько раз в этом классе

2020-06-02 12:35 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/profiles/service/ProfileServiceImpl.java
> +        if (currentUserDetails != null) {
По хорошему, у тебя в сервис должны попадать гарантировано корректные параметры (они как минимум, не должны быть null). Подобную валидацию можно делать в контроллере

2020-06-02 12:35 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/profiles/service/ProfileServiceImpl.java
> +            isFollow = user.getSubscribers().contains(currentUser);
Не вижу смысла в этой переменной, ты можешь заинлайнинть это выражение в конструктор ProfileDto

2020-06-02 12:35 UTC, AndreyElagin commented on src/main/java/com/github/mrptqp/realworld/profiles/service/ProfileServiceImpl.java
> +    public ProfileDtoWrapper unfollow(ConduitUserDetails currentUserDetails, String username) {
Думал ли ты на тему возможных проблем с консистентностью при одновременных вызвовах follow и unfollow?

2020-07-28 11:19 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/profiles/service/ProfileServiceImpl.java
> +        if (currentUserDetails != null) {
А тут, видишь, у меня логика зашита, потому что аутентификация в этом вопросе опциональна. Тобишь, даже если незалогиненный юзер попросит инфу о профайле, то я должен ее предоставить (разница будет только в том, что залогиненный юзер увидит, подписан ли он на юзера, профайл которого он запрашивает)

2020-07-28 11:19 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/profiles/service/ProfileServiceImpl.java
> +                ));
Исправлено

2020-07-28 11:24 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/profiles/service/ProfileServiceImpl.java
> +            isFollow = user.getSubscribers().contains(currentUser);
Заинлайнил 55a6bea3fc1f929f55b85f45f686282caec5bbab

2020-07-28 11:30 UTC, mrPTqp commented on src/main/java/com/github/mrptqp/realworld/profiles/service/ProfileServiceImpl.java
> +    public ProfileDtoWrapper unfollow(ConduitUserDetails currentUserDetails, String username) {
Конечно нет, пока ты не сказал 89d6b2a327abf2b81da98d78ed70cef9fda09558

2020-07-28 13:47 UTC, daddyingrave approved these changes

2020-07-29 12:42 UTC, merged